using System.Text.Json.Serialization;

namespace Salad.Cloud.SDK.Models;

/// <summary>Represents an API error</summary>
public class ProblemDetails
{
    /// <value>The human-readable explanation specific to this occurrence of the error.</value>
    [JsonPropertyName("detail"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Detail { get; init; }

    /// <value>The URI reference that identifies the specific occurrence of the error.</value>
    [JsonPropertyName("instance"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Instance { get; init; }

    /// <value>The HTTP status code generated by the origin server for this occurrence of the error.</value>
    [JsonPropertyName("status"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Status { get; init; }

    /// <value>The short, human-readable summary of the error type.</value>
    [JsonPropertyName("title"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Title { get; init; }

    /// <value>The URI reference that identifies the error type.</value>
    [JsonPropertyName("type"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Type_ { get; init; }

    // Constructor with defaults applied
    public ProblemDetails(
        string? detail = null,
        string? instance = null,
        long? status = null,
        string? title = null,
        string? type = null
    ) { }

    public override string ToString()
    {
        return $"{nameof(ProblemDetails)} {{Detail = {Detail}, Instance = {Instance}, Status = {Status}, Title = {Title}, Type_ = {Type_}}}";
    }
}
